### ISSUE TITLE
Not Showing Comments

### ISSUE THREAD

**Issue by gosakamu** [segmentio/terraform-docs#32] opened 2017-08-02 07:58 UTC
Hey,
I downloaded terraform-docs for **Windows** and executed your example file. Unfortunatly it is not showing the comment section. This is my command and the output.

` terraform-docs md moddocutest\`

> {                                                                   
  "Comment": "",                                                    
  "Inputs": [                                                       
    {                                                               
      "Name": "amis",                                               
      "Description": "",                                            
      "Default": {                                                  
        "Type": "map",                                              
        "Literal": ""                                               
      }                                                             
    },                                                              
    {                                                               
      "Name": "security_group_ids",                                 
      "Description": "",                                            
      "Default": {                                                  
        "Type": "string",                                           
        "Literal": "sg-a, sg-b"                                     
      }                                                             
    },                                                              
    {                                                               
      "Name": "subnet_ids",                                         
      "Description": "a comma-separated list of subnet IDs",        
      "Default": null                                               
    }                                                               
  ],                                                                
  "Outputs": [                                                      
    {                                                               
      "Name": "vpc_id",                                             
      "Description": "The VPC ID.\n"                                
    }                                                               
  ]                                                                 
}                                                                   

Is there anything I can try/check why it isn't working? Additionally I really like the idea of the project. Thank you.

**Comment by yields** [comment] 2017-08-02 17:38
It depends how the header comment is written, is your comment similar to [`_example/main.tf`](https://github.com/segmentio/terraform-docs/blob/master/_example/main.tf)?
It must start with [`/**`](https://github.com/segmentio/terraform-docs/blob/master/doc/doc.go#L240).

**Comment by gosakamu** [comment] 2017-08-03 04:15
I downloaded the raw main.tf. The comment starts with /** has a * on each line and ends with */

I was able to test it on Mac and on Linux with Go and it shows the comment. The Windows .exe is not working correctly. I added the path to terraform-docs.exe to the system PATH and also tried it executing the .exe directly. 

I was thinking about installing go and then try running it on Windows via go. Does this make sense?

**Comment by yields** [comment] 2017-08-16 03:55
hmm, i think it's the newline difference? `\r\n` or whatever on windows and `\n` on unix systems?
but unsure, unfortunately i don't have a windows machine to fix this :/

**Comment by cyberious** [comment] 2017-12-18 18:51
I have tested this on a Mac as well copy and pasting the code from main.tf and still no doc comments

**Comment by cyberious** [comment] 2017-12-18 18:53
With terraform-docs json test.tf I am even getting an empty comment section.
~~~json
{
  "Comment": "",
  "Inputs": [
    {
      "Name": "amis",
      "Description": "",
      "Default": {
        "Type": "map",
        "Literal": ""
      },
      "Type": "string"
    },
    {
      "Name": "security_group_ids",
      "Description": "",
      "Default": {
        "Type": "string",
        "Literal": "sg-a, sg-b"
      },
      "Type": "string"
    },
    {
      "Name": "subnet_ids",
      "Description": "a comma-separated list of subnet IDs",
      "Default": null,
      "Type": "string"
    }
  ],
  "Outputs": [
    {
      "Name": "vpc_id",
      "Description": "The VPC ID.\n"
    }
  ]
}
~~~

**Comment by cyberious** [comment] 2017-12-18 19:32
Ok, I see my issue but not sure if this is intended that only if the file is `main.tf` will it respect and output the comments.

**Comment by leftathome** [comment] 2018-01-18 22:28
For what it's worth, that behavior is consistent on Linux and Mac as well in the versions I've used - main.tf's comment header is the only one that gets added to the output.

I actually just came across a case where I could see wanting to get a little fancier with that, so I thought I'd check the repo again to see if anyone else was thinking along those lines...

**Comment by tlanfer** [comment] 2018-03-23 14:34
I just came across the same behavious.
Turns out, if u run terraform-docs from within my module directory as `terraform-docs md .` i get comments, if i run it from the _surrounding_ folder `terraform-docs md some-module` i do not get comments. Is maybe the detection of the name "main.tf" broken?

**Comment by garettmd** [comment] 2018-08-10 16:28
Here's the portion that's limiting the comments to a `main.tf`. I think a better approach would be to gather comments from all files (even if it's just the first occurrence of a `/**…*/` block in a file) and place those in a comments section

https://github.com/segmentio/terraform-docs/blob/7110697c09f357127900dd48381b29f3fabe863c/doc/doc.go#L80-L82

**Comment by metmajer** [comment] 2018-09-26 18:46
The issue is resolved by the above PR.

**Closed by metmajer** 2018-09-26 18:46 UTC
