### ISSUE TITLE
MarshalJSON for type types.String: invalid character 'd' in string escape code

### ISSUE THREAD

**Issue by VR6Pete** [segmentio/terraform-docs#259] opened 2020-05-11 16:29 UTC
Hi, terraform-docs throws an error when hitting the below variable:

Error: 

Error: template: inputs:10:118: executing "inputs" at <.GetValue>: error calling GetValue: json: error calling MarshalJSON for type types.String: invalid character 'd' in string escape code

offending block:

variable "push_rules_branch_name_regex" {
  type        = string
  default     = "^(release\\/\\d+\\.\\d+)|((feature|hotfix|bugfix|renovate)\\/.+)|((cherry-pick|revert)-.+)$"
  description = "branch name. used if project_push_rules_enabled = true"
}

Thanks.

Pete

**Comment by khos2ow** [comment] 2020-05-11 16:42
duplicate of #238

**Closed by khos2ow** 2020-05-11 16:42 UTC
Labels: bug
