### ISSUE TITLE
Markdown table to keep newlines

### ISSUE THREAD

**Issue by pielu** [segmentio/terraform-docs#171] opened 2020-01-17 20:26 UTC
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

I was wondering if the heredoc's newlines should be preserved when producing markdown table?

#### Actual Behavior

Right now newlines are gone making tables' e.g. description fields that use heredoc to wrap. 

```
| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:-----:|
| internet\_gateway | tags - (Optional) A mapping of tags to assign to the resource. | `map` | `{}` | no |
| subnet | availability\_zone - (Optional) The AZ for the subnet. bits - (Required) New bits used for calculating cidrsubnets off of VPC's cidr\_block. name - (Required) Unique name for the subnet public - (Optional) Specify true to indicate that instances launched into the subnet should be assigned a public IP address. Default is false. tags - (Optional) A mapping of tags to assign to the resource.
```

Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

Maintain heredoc newlines (e.g. add <br/> - I understand newlines in md are somewhat brittle territory...)

```
| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:-----:|
| internet\_gateway | tags - (Optional) A mapping of tags to assign to the resource. | `map` | `{}` | no |
| subnet | availability\_zone - (Optional) The AZ for the subnet.<br/> bits - (Required) New bits used for calculating cidrsubnets off of VPC's cidr\_block.<br/> name - (Required) Unique name for the subnet<br/>public - (Optional) Specify true to indicate that instances launched into the subnet should be assigned a public IP address. Default is false.<br/>tags - (Optional) A mapping of tags to assign to the resource.
```

### Replication Case

Tell us which steps to take to replicate your problem.
```
variable "subnet" {
  description = <<-EOF
    availability_zone - (Optional) The AZ for the subnet.
    bits - (Required) New bits used for calculating cidrsubnets off of VPC's cidr_block.
    name - (Required) Unique name for the subnet
    public - (Optional) Specify true to indicate that instances launched into the subnet should be assigned a public IP address. Default is false.
    tags - (Optional) A mapping of tags to assign to the resource.
  EOF
```
### Version

0.8.0-rc.3

**Comment by khos2ow** [comment] 2020-01-17 20:43
This looks like a duplicate of #167.
Also we've just released `v0.8.0`, can you download the latest [release](https://github.com/segmentio/terraform-docs/releases) and give this another try and reopen the issue if you still have some problem.

**Closed by khos2ow** 2020-01-17 20:43 UTC
