### ISSUE TITLE
Pinned Terraform Versions

### ISSUE THREAD

**Issue by VR6Pete** [segmentio/terraform-docs#205] opened 2020-02-21 14:49 UTC
### Prerequisites

Put an `x` into the box that applies:

- [] This issue describes a bug.
- [ x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

I see there is support to output provider versions, we use pinned terraform versions with some of our modules and It would be good if terraform-docs can capture the required_version from the terraform block. 

```
terraform {
  required_version = ">= 0.12.0"

  required_providers {
    aws = ">= 2.43.0"
  }
}
```

**Comment by khos2ow** [comment] 2020-02-21 16:42
Thank you, this is duplicate of #159.

**Closed by khos2ow** 2020-02-21 16:42 UTC
