### ISSUE TITLE
Is this project compatible with terraform 0.12?

### ISSUE THREAD

**Issue by vara-bonthu** [segmentio/terraform-docs#129] opened 2019-10-21 09:48 UTC
### Prerequisites

Put an `x` into the box that applies:

- [ x] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

terraform-docs markdown document ./db_parameter_group failing with the following error...

2019/10/21 09:55:05 At 2:12: Unknown token: 2:12 IDENT var.aws_region
2019/10/21 10:44:48 At 13:17: Unknown token: 13:17 IDENT coalesce

Just wondering if this project supports Terraform 0.12

#### Actual Behavior

Briefly describe what happened.

```
```

Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

Briefly describe what you expected to happen.

```
```

### Replication Case

Tell us which steps to take to replicate your problem.

1. ...
2. ...
3. ...

### Version

You can get this information via `terraform-docs --version`.
0.6.0

**Comment by mbarrien** [comment] 2019-10-21 09:52
Duplicate of #62

**Comment by gdurandvadas** [comment] 2019-10-30 12:19
I think the current version should advice that doesn't support 0.12 at least. Anyone using 0.12 can't document with this tool :)

**Comment by mxlan** [comment] 2019-11-13 15:47
Just recently acquired version 0.6.0, I am running terraform 0.12.7 and unable to generate docs using the tool. Just as a verbal confirmation to @gdurandvadas .

```
2019/11/13 10:45:40 At 31:12: Unknown token: 31:12 IDENT local.log_bucket_name
```

**Comment by BrunIF** [comment] 2019-11-15 07:36
```
2019/11/15 09:31:43 At 34:17: Unknown token: 34:17 IDENT map
2019/11/15 09:34:48 At 30:19: Unknown token: 30:19 IDENT var.amis
```

**Comment by tbugfinder** [comment] 2019-11-15 19:06
Check for workarounds:
https://github.com/segmentio/terraform-docs/pull/113

**Comment by khos2ow** [comment] 2019-11-21 01:42
As stated above support for Terraform 0.12 is currently work in progress (#62) and for the time being workaround was suggested https://github.com/segmentio/terraform-docs/pull/113#issuecomment-519734867

**Closed by khos2ow** 2019-11-21 01:42 UTC
